=== WorldHealthOrganization/tng-cdn-dev/schema/did-trustlist-syntax-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/WorldHealthOrganization/tng-cdn-dev/refs/heads/main/schema/did-trustlist-syntax-schema.json",
  "title": "DID Document Syntax Schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "@context": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "id": {
      "type": "string"
    },
    "controller": {
      "type": "string"
    },
    "verificationMethod": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "controller": {
            "type": "string"
          },

          "publicKeyJwk": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "kty": { "type": "string" },
              "kid": { "type": "string" },
              "x5c": {
                "type": "array",
                "items": { "type": "string" }
              },
              "crv": { "type": "string" },
              "x": { "type": "string" },
              "y": { "type": "string" },
              "e": { "type": "string" },
              "n": { "type": "string" }
            },
            "required": ["kty", "kid", "x5c"]
          },

          "domain": {
            "type": "string"
          },
          "participant": {
            "type": "string"
          },
          "keyusage": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "type",
          "controller",
          "publicKeyJwk",
          "domain",
          "participant",
          "keyusage"
        ]
      }
    },

    "proof": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": { "type": "string" },
        "created": { "type": "string" },
        "nonce": { "type": "string" },
        "proofPurpose": { "type": "string" },
        "verificationMethod": { "type": "string" },
        "jws": { "type": "string" }
      },
      "required": [
        "type",
        "created",
        "nonce",
        "proofPurpose",
        "verificationMethod",
        "jws"
      ]
    }
  },
  "required": [
    "@context",
    "id",
    "controller",
    "verificationMethod",
    "proof"
  ]
}

=== WorldHealthOrganization/tng-cdn-dev/v2/trustlist/-/XL/did.json
{"@context":["https://www.w3.org/ns/did/v1","https://w3id.org/security/suites/jws-2020/v1","https://worldhealthorganization.github.io/smart-trust/tng-additional-context/v1"],"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:-:XL","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:-","verificationMethod":[{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:-:XL:SCA#2RIYRNJvPBg=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:-","publicKeyJwk":{"kty":"EC","kid":"2RIYRNJvPBg=","x5c":["MIICFTCCAbugAwIBAgIUN2LeFtoIJ9RnfWbtm2KmavrqVH8wCgYIKoZIzj0EAwIwZzELMAkGA1UEBhMCWEwxCzAJBgNVBAgMAk1UMREwDwYDVQQHDAhTQU5USUFHTzEPMA0GA1UECgwGQ1JFQVRFMQwwCgYDVQQLDANSJkQxGTAXBgNVBAMMEE5hdGlvblhMX1ROUF9TQ0EwHhcNMjMwOTI4MTczMDU0WhcNMjcwOTI4MTczMDU0WjBnMQswCQYDVQQGEwJYTDELMAkGA1UECAwCTVQxETAPBgNVBAcMCFNBTlRJQUdPMQ8wDQYDVQQKDAZDUkVBVEUxDDAKBgNVBAsMA1ImRDEZMBcGA1UEAwwQTmF0aW9uWExfVE5QX1NDQTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABADa29gT9IMfh6XgAjNUFA/ckQEpjkHFCm3rAK47gNZ2nNIqutk15wILxLT3Zf6aMNwPcEn38iFaJaqKSQr663+jRTBDMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBQOLQgcF/crtl6LuK9tYr650XygFjAKBggqhkjOPQQDAgNIADBFAiEAj2JHlg2ds+N5GRum3X1p6wUDppwUJjqtJRS/xxzU0fYCIFb56xpwL/nVQ+2/xyOlN9aVS+Gbq8u5+r1HePKGeMEJ"],"crv":"P-256","x":"ANrb2BP0gx-HpeACM1QUD9yRASmOQcUKbesArjuA1nY","y":"AJzSKrrZNecCC8S092X-mjDcD3BJ9_IhWiWqikkK-ut_"},"domain":"DCC","participant":"XL","keyusage":"SCA"},{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:-:XL:SCA#3wiKBCaFuok=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:-","publicKeyJwk":{"kty":"EC","kid":"3wiKBCaFuok=","x5c":["MIICFTCCAbugAwIBAgIUZg3GCdgTYDbAORHyethAud82ETAwCgYIKoZIzj0EAwIwZzELMAkGA1UEBhMCWEwxCzAJBgNVBAgMAk1UMREwDwYDVQQHDAhTQU5USUFHTzEPMA0GA1UECgwGQ1JFQVRFMQwwCgYDVQQLDANSJkQxGTAXBgNVBAMMEE5hdGlvblhMX1ROUF9TQ0EwHhcNMjMxMDA0MTUyMTI3WhcNMjcxMDA0MTUyMTI3WjBnMQswCQYDVQQGEwJYTDELMAkGA1UECAwCTVQxETAPBgNVBAcMCFNBTlRJQUdPMQ8wDQYDVQQKDAZDUkVBVEUxDDAKBgNVBAsMA1ImRDEZMBcGA1UEAwwQTmF0aW9uWExfVE5QX1NDQTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABOUht3wSLNl4Ae1/wRUfVY1CTKrOog+vuIyrIUOdCcIumeAz8AckJdfVTN5+sVcGkw1T8kQFMNaf5lCv8QH6jXWjRTBDMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBQmHPdh8sTGTj8CpqhvKV/RXTwIujAKBggqhkjOPQQDAgNIADBFAiAOsxW3y3KitIQUu3NnKVL79Hc4wuAESSfDN2H6NGtCxQIhAKAmub3n49gFLDFcpc4rOX9GgUGvf5XEbzuXtMADgsll"],"crv":"P-256","x":"AOUht3wSLNl4Ae1_wRUfVY1CTKrOog-vuIyrIUOdCcIu","y":"AJngM_AHJCXX1UzefrFXBpMNU_JEBTDWn-ZQr_EB-o11"},"domain":"RACSEL-DDVC","participant":"XL","keyusage":"SCA"},{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:-:XL:SCA#8nAX0I7m7A0=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:-","publicKeyJwk":{"kty":"EC","kid":"8nAX0I7m7A0=","x5c":["MIICDDCCAbOgAwIBAgIUWizt1UMJI5R+p7d99hVV+HCbLAUwCgYIKoZIzj0EAwIwYzELMAkGA1UEBhMCWEwxCzAJBgNVBAgMAk1UMREwDwYDVQQHDAhTYW50aWFnbzEQMA4GA1UECgwHTEFDUGFzczEQMA4GA1UECwwHTEFDUGFzczEQMA4GA1UEAwwHTEFDUGFzczAeFw0yMzA5MDUxMjI5NTNaFw0yNzA5MDUxMjI5NTNaMGMxCzAJBgNVBAYTAlhMMQswCQYDVQQIDAJNVDERMA8GA1UEBwwIU2FudGlhZ28xEDAOBgNVBAoMB0xBQ1Bhc3MxEDAOBgNVBAsMB0xBQ1Bhc3MxEDAOBgNVBAMMB0xBQ1Bhc3MwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAS6oX06i1IFeRR/G2yUtVWFxaknWsZBFGh7rsEiYzRYKh4Q4+kWbXTNdlnCBWWeg2pkTtn8yY8lBiZzE3VOdIzAo0UwQzASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQU/ElE7e3KGwtsuerSyFOrod1UxDkwCgYIKoZIzj0EAwIDRwAwRAIgEvuyBlQTNHXo+mzXWiFf2dzrU27ZovslezGL+2dpGjECIC8qbgvYpF6Smo4nBC+tzU2zxiOeRewqfpzAQqEvo4mF"],"crv":"P-256","x":"ALqhfTqLUgV5FH8bbJS1VYXFqSdaxkEUaHuuwSJjNFgq","y":"HhDj6RZtdM12WcIFZZ6DamRO2fzJjyUGJnMTdU50jMA"},"domain":"DCC","participant":"XL","keyusage":"SCA"},{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:-:XL:SCA#MD93Io4g9GE=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:-","publicKeyJwk":{"kty":"EC","kid":"MD93Io4g9GE=","x5c":["MIICIDCCAcegAwIBAgIUeo8sCjTu/O8lEw5+msfG6Ss/qmAwCgYIKoZIzj0EAwIwbTELMAkGA1UEBhMCWEwxEzARBgNVBAgMClRlc3QgU3RhdGUxEzARBgNVBAcMCkNhbGlmb3JuaWExDzANBgNVBAoMBkNyZWF0ZTEMMAoGA1UECwwDUiZEMRUwEwYDVQQDDAxOYXRpb25YQ19UTlAwHhcNMjUwOTA1MjIyODExWhcNMjkwOTA1MjIyODExWjBtMQswCQYDVQQGEwJYTDETMBEGA1UECAwKVGVzdCBTdGF0ZTETMBEGA1UEBwwKQ2FsaWZvcm5pYTEPMA0GA1UECgwGQ3JlYXRlMQwwCgYDVQQLDANSJkQxFTATBgNVBAMMDE5hdGlvblhDX1ROUDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGyu+Fiohg8APhNR8M0ES2qC0bMXLQb8QCoAakFJ0yubhJku+Q1hJE1uXIJo1JMMMSqhWkH6ZLaroQgCrXEfeXqjRTBDMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBQ6ucEi0XUzbXD4njquKtEXAtxYnzAKBggqhkjOPQQDAgNHADBEAiAYInGL6MNXhsxaHULBN7qoGdZU0fCUcU/Ga015QzDH6gIged0zuy/RlSqRb8BGgMwmJ9m/8WT82FpG2obN/QxPMGI="],"crv":"P-256","x":"bK74WKiGDwA-E1HwzQRLaoLRsxctBvxAKgBqQUnTK5s","y":"AISZLvkNYSRNblyCaNSTDDEqoVpB-mS2q6EIAq1xH3l6"},"domain":"PH4H","participant":"XL","keyusage":"SCA"},{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:-:XL:DSC#aGgTqS0ILXs=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:-","publicKeyJwk":{"kty":"EC","kid":"aGgTqS0ILXs=","x5c":["MIICoTCCAkegAwIBAgIUXyW8Eb8M4PiKkdr7IOs76K1KvgMwCgYIKoZIzj0EAwIwbTELMAkGA1UEBhMCWEwxEzARBgNVBAgMClRlc3QgU3RhdGUxEzARBgNVBAcMCkNhbGlmb3JuaWExDzANBgNVBAoMBkNyZWF0ZTEMMAoGA1UECwwDUiZEMRUwEwYDVQQDDAxOYXRpb25YQ19UTlAwHhcNMjUwOTE1MTYxMTQyWhcNMjcwOTE1MTYxMTQyWjBtMQswCQYDVQQGEwJYTDETMBEGA1UECAwKVGVzdCBTdGF0ZTETMBEGA1UEBwwKQ2FsaWZvcm5pYTEPMA0GA1UECgwGQ3JlYXRlMQwwCgYDVQQLDANSJkQxFTATBgNVBAMMDE5hdGlvblhDX1ROUDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABAJZ5WloyvRU9HXS5mHTLNYanyG8jh6loevfFNJA3NrmYObSLqZwON08a3wOUQrINll7MuwNx2jX7BCUlBK97P+jgcQwgcEwDgYDVR0PAQH/BAQDAgeAMB0GA1UdDgQWBBTiKURePY7GSWRC5xvyRsNY2Z0s1DAfBgNVHSMEGDAWgBQ6ucEi0XUzbXD4njquKtEXAtxYnzA9BgNVHR8ENjA0MDKgMKAuhixodHRwOi8vY3JsLmV4YW1wbGVkb21haW4uZXhhbXBsZS9DUkwvU0NBLmNybDAwBgNVHSUEKTAnBgsrBgEEAY43j2UBAQYLKwYBBAGON49lAQIGCysGAQQBjjePZQEDMAoGCCqGSM49BAMCA0gAMEUCIQCCVvtzAJxWfchtSLBRLR6DL1aJXrH7j+KamfT8y9ksBwIgBVVUTlhwLk+cRKYffZmAX50YibCt9kWpHPVcekzDPy0="],"crv":"P-256","x":"AlnlaWjK9FT0ddLmYdMs1hqfIbyOHqWh698U0kDc2uY","y":"YObSLqZwON08a3wOUQrINll7MuwNx2jX7BCUlBK97P8"},"domain":"DCC","participant":"XL","keyusage":"DSC"},{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:-:XL:SCA#hRJFN+daQrI=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:-","publicKeyJwk":{"kty":"EC","kid":"hRJFN+daQrI=","x5c":["MIICAjCCAaegAwIBAgIUKF4lTmfdzK4G2N70l0ZsuqwnvCUwCgYIKoZIzj0EAwIwXTELMAkGA1UEBhMCWEwxCzAJBgNVBAgMAk1UMREwDwYDVQQHDAhTYW50aWFnbzEPMA0GA1UECgwGQ3JlYXRlMQwwCgYDVQQLDANSJkQxDzANBgNVBAMMBkNyZWF0ZTAeFw0yNDA5MTAyMDUxMjhaFw0yODA5MTAyMDUxMjhaMF0xCzAJBgNVBAYTAlhMMQswCQYDVQQIDAJNVDERMA8GA1UEBwwIU2FudGlhZ28xDzANBgNVBAoMBkNyZWF0ZTEMMAoGA1UECwwDUiZEMQ8wDQYDVQQDDAZDcmVhdGUwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATwTvXHsCOZVe8cux/7YJF1Z5fTQJBWjiOlosaXWxi+72l4i8PECtFyEV+s1vk8ynZ8BSlEanXA7yWnzXf1mZsHo0UwQzASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUltU4J1etuXVuGvSffa+h2q0xeGowCgYIKoZIzj0EAwIDSQAwRgIhAMbyCD/0VopFYhpYdxUWomzSwlH5iqBlgym9DmsTeUvwAiEA3CyeKGAibv5NIj7EkGazFTP+gvqAvPAqViVNty9TJWo="],"crv":"P-256","x":"APBO9cewI5lV7xy7H_tgkXVnl9NAkFaOI6WixpdbGL7v","y":"aXiLw8QK0XIRX6zW-TzKdnwFKURqdcDvJafNd_WZmwc"},"domain":"PH4H","participant":"XL","keyusage":"SCA"},{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:-:XL:DSC#lkxZC7WEOIs=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:-","publicKeyJwk":{"kty":"EC","kid":"lkxZC7WEOIs=","x5c":["MIICoTCCAkegAwIBAgIUXyW8Eb8M4PiKkdr7IOs76K1KvgQwCgYIKoZIzj0EAwIwbTELMAkGA1UEBhMCWEwxEzARBgNVBAgMClRlc3QgU3RhdGUxEzARBgNVBAcMCkNhbGlmb3JuaWExDzANBgNVBAoMBkNyZWF0ZTEMMAoGA1UECwwDUiZEMRUwEwYDVQQDDAxOYXRpb25YQ19UTlAwHhcNMjUwOTE1MTYzNTMwWhcNMjcwOTE1MTYzNTMwWjBtMQswCQYDVQQGEwJYTDETMBEGA1UECAwKVGVzdCBTdGF0ZTETMBEGA1UEBwwKQ2FsaWZvcm5pYTEPMA0GA1UECgwGQ3JlYXRlMQwwCgYDVQQLDANSJkQxFTATBgNVBAMMDE5hdGlvblhDX1ROUDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFgLQ2NpmIdaotfGiR0DRQ3OXWj6nTS0aqUphzXVjCi6A+kULLvX3qB/1bDLnrvMSvpVqzzSq0GocSA+4f2OWxKjgcQwgcEwDgYDVR0PAQH/BAQDAgeAMB0GA1UdDgQWBBQlEhNfCSe2r4WafE/EyFSY0TTAIDAfBgNVHSMEGDAWgBQ6ucEi0XUzbXD4njquKtEXAtxYnzA9BgNVHR8ENjA0MDKgMKAuhixodHRwOi8vY3JsLmV4YW1wbGVkb21haW4uZXhhbXBsZS9DUkwvU0NBLmNybDAwBgNVHSUEKTAnBgsrBgEEAY43j2UBAQYLKwYBBAGON49lAQIGCysGAQQBjjePZQEDMAoGCCqGSM49BAMCA0gAMEUCIQCrOl1QmsOhzAXjYoTj26yVogte53eNqOKc6qrbtfZIGwIgH+lKLGJTo7wlyutgQ2EF49Bj7UFu3w9vP5Ri/Hp0voU=","MIICIDCCAcegAwIBAgIUeo8sCjTu/O8lEw5+msfG6Ss/qmAwCgYIKoZIzj0EAwIwbTELMAkGA1UEBhMCWEwxEzARBgNVBAgMClRlc3QgU3RhdGUxEzARBgNVBAcMCkNhbGlmb3JuaWExDzANBgNVBAoMBkNyZWF0ZTEMMAoGA1UECwwDUiZEMRUwEwYDVQQDDAxOYXRpb25YQ19UTlAwHhcNMjUwOTA1MjIyODExWhcNMjkwOTA1MjIyODExWjBtMQswCQYDVQQGEwJYTDETMBEGA1UECAwKVGVzdCBTdGF0ZTETMBEGA1UEBwwKQ2FsaWZvcm5pYTEPMA0GA1UECgwGQ3JlYXRlMQwwCgYDVQQLDANSJkQxFTATBgNVBAMMDE5hdGlvblhDX1ROUDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGyu+Fiohg8APhNR8M0ES2qC0bMXLQb8QCoAakFJ0yubhJku+Q1hJE1uXIJo1JMMMSqhWkH6ZLaroQgCrXEfeXqjRTBDMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBQ6ucEi0XUzbXD4njquKtEXAtxYnzAKBggqhkjOPQQDAgNHADBEAiAYInGL6MNXhsxaHULBN7qoGdZU0fCUcU/Ga015QzDH6gIged0zuy/RlSqRb8BGgMwmJ9m/8WT82FpG2obN/QxPMGI="],"crv":"P-256","x":"WAtDY2mYh1qi18aJHQNFDc5daPqdNLRqpSmHNdWMKLo","y":"A-kULLvX3qB_1bDLnrvMSvpVqzzSq0GocSA-4f2OWxI"},"domain":"PH4H","participant":"XL","keyusage":"DSC"}],"proof":{"type":"JsonWebSignature2020","created":"2026-01-04T06:00:21Z","nonce":"IwTUszhgvMeo8C4IJhEqbV47jkBLGpp9","proofPurpose":"assertionMethod","verificationMethod":"did:web:raw.githubusercontent.com:WorldHealthOrganization:tng-participants-dev:main:WHO:signing:DID","jws":"eyJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdLCJhbGciOiJFUzI1NiJ9..MEUCIFxdMZXUhTk6Ni-faqjgQscto6uaPJmyS3TLgxrK3W9nAiEA73aC3fBzw90Ni0Xjrq-oZ6uNIi87bfKKgzmoA-HSJDQ"}}

=== WorldHealthOrganization/tng-cdn-dev/v2/trustlist/PH4H/XJ/DSC/did.json
{"@context":["https://www.w3.org/ns/did/v1","https://w3id.org/security/suites/jws-2020/v1"],"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H:XJ:DSC","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H:XJ","verificationMethod":[{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H:XJ:DSC#I1BAX8FATLs=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H:XJ","publicKeyJwk":{"kty":"EC","kid":"I1BAX8FATLs=","x5c":["MIICpjCCAkygAwIBAgIURDYp9AbORfgP9bf+ObdVpZmPhDQwCgYIKoZIzj0EAwIwajELMAkGA1UEBhMCWEoxEzARBgNVBAgMClRlc3QgU3RhdGUxDzANBgNVBAcMBkdlbmV2YTEMMAoGA1UECgwDV0hPMQwwCgYDVQQLDANSJkQxGTAXBgNVBAMMEE5hdGlvblhKX1ROUF9TQ0EwHhcNMjQxMDAzMTI0OTAwWhcNMjYxMDAzMTI0OTAwWjB1MQswCQYDVQQGEwJYSjETMBEGA1UECAwKVGVzdCBTdGF0ZTEPMA0GA1UEBwwGR2VuZXZhMQwwCgYDVQQKDANXSE8xDDAKBgNVBAsMA1ImRDEkMCIGA1UEAwwbSGVhbHRoIEFkbWluaXN0cmF0aW9uIG9mIFhKMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAED2DolXPl+/M2H+vYoh2DuC+eeElyV7Ah+tXAYP7XjEgF3XrH1mNfzyUqoGu0FduPWhvxANA/da38f+9K8K30oqOBxDCBwTAOBgNVHQ8BAf8EBAMCB4AwHQYDVR0OBBYEFIoZa0IBL5BwoiTG3W2KwbK+eT3ZMB8GA1UdIwQYMBaAFBgehL4frCZdyg4bY5wayH0gXujiMD0GA1UdHwQ2MDQwMqAwoC6GLGh0dHA6Ly9jcmwuZXhhbXBsZWRvbWFpbi5leGFtcGxlL0NSTC9TQ0EuY3JsMDAGA1UdJQQpMCcGCysGAQQBjjePZQEBBgsrBgEEAY43j2UBAgYLKwYBBAGON49lAQMwCgYIKoZIzj0EAwIDSAAwRQIhALNDwRKfOuYoL24AzCH1i5yhUIhD3AMODBjQU+W9qLABAiAop0w+ExucFOHjt/mQWwd9yeFfPcepcVbd54yM10MdMg==","MIICGzCCAcGgAwIBAgIUWyouM/fxtzeZyzVwzWZhADcTRW0wCgYIKoZIzj0EAwIwajELMAkGA1UEBhMCWEoxEzARBgNVBAgMClRlc3QgU3RhdGUxDzANBgNVBAcMBkdlbmV2YTEMMAoGA1UECgwDV0hPMQwwCgYDVQQLDANSJkQxGTAXBgNVBAMMEE5hdGlvblhKX1ROUF9TQ0EwHhcNMjQxMDAyMTMyMTA3WhcNMjgxMDAyMTMyMTA3WjBqMQswCQYDVQQGEwJYSjETMBEGA1UECAwKVGVzdCBTdGF0ZTEPMA0GA1UEBwwGR2VuZXZhMQwwCgYDVQQKDANXSE8xDDAKBgNVBAsMA1ImRDEZMBcGA1UEAwwQTmF0aW9uWEpfVE5QX1NDQTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABCugeSkBX+/Y76WZuihSJJQsGZg9Qn5bWBTl0AQr7X2uLf0jyKMKO5rmvZW/koRaM+E6tVFYZ7ljo9e8MWsMp2CjRTBDMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBQYHoS+H6wmXcoOG2OcGsh9IF7o4jAKBggqhkjOPQQDAgNIADBFAiB5BMv0I39j405EzluroVv8iKjmSCodB16TVgV8lxFC4wIhAKVy5hLN5YCjVo9FLx5ITjbyChuplM8UHCwpvX/+BW0m"],"crv":"P-256","x":"D2DolXPl-_M2H-vYoh2DuC-eeElyV7Ah-tXAYP7XjEg","y":"Bd16x9ZjX88lKqBrtBXbj1ob8QDQP3Wt_H_vSvCt9KI"},"domain":"PH4H","participant":"XJ","keyusage":"DSC"}],"proof":{"type":"JsonWebSignature2020","created":"2025-07-12T12:00:22Z","nonce":"y5PQlzRhlwMj1ks28LhZzi38Kes6te2F","proofPurpose":"assertionMethod","verificationMethod":"did:web:raw.githubusercontent.com:WorldHealthOrganization:tng-participants-dev:main:WHO:signing:DID","jws":"eyJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdLCJhbGciOiJFUzI1NiJ9..MEQCIGpER1-cGPIT66GNcH7HmGuBMFhQoAOcGrJZtqtCPLavAiBPaKhfIAXJVNo_7nffq6b5X1zY68VcSkvBjE3usYGFvA"}}

=== WorldHealthOrganization/tng-cdn-dev/v2/trustlist/IPS/XA/did.json
{"@context":["https://www.w3.org/ns/did/v1","https://w3id.org/security/suites/jws-2020/v1","https://worldhealthorganization.github.io/smart-trust/tng-additional-context/v1"],"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:IPS:XA","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:IPS","verificationMethod":[{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:IPS:XA:DSC#pkALteuRyCY=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:IPS","publicKeyJwk":{"kty":"EC","kid":"pkALteuRyCY=","x5c":["MIICujCCAmCgAwIBAgIUD9k1Q64Eav5r07DQ4Gff/7h7r6YwCgYIKoZIzj0EAwIwdDELMAkGA1UEBhMCWEExFDASBgNVBAgMC1hYQSBDb3VudHJ5MRgwFgYDVQQHDA9YQSBDYXBpdG9sIENpdHkxDDAKBgNVBAoMA1dITzEMMAoGA1UECwwDUiZEMRkwFwYDVQQDDBBOYXRpb25YQV9UTlBfU0NBMB4XDTI0MDgwMjEzNDYwNFoXDTI2MDgwMjEzNDYwNFowfzELMAkGA1UEBhMCWEExFDASBgNVBAgMC1hYQSBDb3VudHJ5MRgwFgYDVQQHDA9YQSBDYXBpdG9sIENpdHkxDDAKBgNVBAoMA1dITzEMMAoGA1UECwwDUiZEMSQwIgYDVQQDDBtIZWFsdGggQWRtaW5pc3RyYXRpb24gb2YgWEEwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASDKWDGfNBTbukclQq5IclHicmif4bcO3BPqpQe7ZWifXGo2YmL1zk/OALnEtADncDn/AlqOeUvHdG20oN9Qu59o4HEMIHBMA4GA1UdDwEB/wQEAwIHgDAdBgNVHQ4EFgQUEJx8fGMtJI49arbr4PojpNr/TQowHwYDVR0jBBgwFoAUoir+zkKsSL7OkG8dPyThX49GLtEwPQYDVR0fBDYwNDAyoDCgLoYsaHR0cDovL2NybC5leGFtcGxlZG9tYWluLmV4YW1wbGUvQ1JML1NDQS5jcmwwMAYDVR0lBCkwJwYLKwYBBAGON49lAQEGCysGAQQBjjePZQECBgsrBgEEAY43j2UBAzAKBggqhkjOPQQDAgNIADBFAiEAsTnM65VZUgaMPdJCD1i4Eo5D29EDhKCJQSOxQd4pARMCIAoeNGihm66wBUa1qCMaAutmn9rILmYodnCemNMjJ+p6"],"crv":"P-256","x":"AIMpYMZ80FNu6RyVCrkhyUeJyaJ_htw7cE-qlB7tlaJ9","y":"cajZiYvXOT84AucS0AOdwOf8CWo55S8d0bbSg31C7n0"},"domain":"IPS","participant":"XA","keyusage":"DSC"}],"proof":{"type":"JsonWebSignature2020","created":"2026-01-04T06:00:11Z","nonce":"r9zP8tKpbyBpqaPIan6BZXjGfrONCgk3","proofPurpose":"assertionMethod","verificationMethod":"did:web:raw.githubusercontent.com:WorldHealthOrganization:tng-participants-dev:main:WHO:signing:DID","jws":"eyJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdLCJhbGciOiJFUzI1NiJ9..MEUCIQDa4zOpoEQvEzN2TnDZDI2pAv1DTBRyhizPBXpHBsBAwAIgP1jttM_EaxjZqAZP03C3KaTGSN7FztKB13O8oxsyyJA"}}

=== WorldHealthOrganization/tng-cdn-dev/v2/trustlist/PH4H/XA/SCA/did.json
{"@context":["https://www.w3.org/ns/did/v1","https://w3id.org/security/suites/jws-2020/v1","https://worldhealthorganization.github.io/smart-trust/tng-additional-context/v1"],"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H:XA:SCA","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H:XA","verificationMethod":[{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H:XA:SCA#/Eg0veXxFzY=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H:XA","publicKeyJwk":{"kty":"EC","kid":"/Eg0veXxFzY=","x5c":["MIICGzCCAcGgAwIBAgIUV9fOwm0PmJmdzPbhlgDwMbeon4YwCgYIKoZIzj0EAwIwajELMAkGA1UEBhMCWEExEzARBgNVBAgMClRlc3QgU3RhdGUxDzANBgNVBAcMBkdlbmV2YTEMMAoGA1UECgwDV0hPMQwwCgYDVQQLDANSJkQxGTAXBgNVBAMMEE5hdGlvblhBX1ROUF9TQ0EwHhcNMjQwOTI2MTg1MDMyWhcNMjgwOTI2MTg1MDMyWjBqMQswCQYDVQQGEwJYQTETMBEGA1UECAwKVGVzdCBTdGF0ZTEPMA0GA1UEBwwGR2VuZXZhMQwwCgYDVQQKDANXSE8xDDAKBgNVBAsMA1ImRDEZMBcGA1UEAwwQTmF0aW9uWEFfVE5QX1NDQTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABAqP53p92SogYMFOXmUQYH+UK5wrwNzTrCyMmuiOtpmeE3eTuW3BN3h1hbS79fRlSmToVSi41Q4oTJQSsnJgLumjRTBDMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBQoP/9IfJbyXXM8OlnDagS1M7jJfDAKBggqhkjOPQQDAgNIADBFAiEA+Fz0eeH7QvxJoclPzva8qHwzoHZ8eRPygaKKDh1ggRgCICl60ioWmA6dPOtWx9uj0+QVUh12yGSBoOr0VIMgg9tq"],"crv":"P-256","x":"Co_nen3ZKiBgwU5eZRBgf5QrnCvA3NOsLIya6I62mZ4","y":"E3eTuW3BN3h1hbS79fRlSmToVSi41Q4oTJQSsnJgLuk"},"domain":"PH4H","participant":"XA","keyusage":"SCA"}],"proof":{"type":"JsonWebSignature2020","created":"2026-01-04T06:00:25Z","nonce":"eMMAZPOtiLTWE2J6rfc2LVPI9l5Hu3wh","proofPurpose":"assertionMethod","verificationMethod":"did:web:raw.githubusercontent.com:WorldHealthOrganization:tng-participants-dev:main:WHO:signing:DID","jws":"eyJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdLCJhbGciOiJFUzI1NiJ9..MEUCIQDhVzBTI0W291wQSkHOjF099LDssYST08_pPqkTR5I8WgIgEVtbqILp43lIDkRGNrQFZqQhLXogG4gELxs3yOAZCU0"}}

=== WorldHealthOrganization/tng-cdn-dev/v2/trustlist/PH4H/XL/DSC/did.json
{"@context":["https://www.w3.org/ns/did/v1","https://w3id.org/security/suites/jws-2020/v1","https://worldhealthorganization.github.io/smart-trust/tng-additional-context/v1"],"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H:XL:DSC","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H:XL","verificationMethod":[{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H:XL:DSC#lkxZC7WEOIs=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H:XL","publicKeyJwk":{"kty":"EC","kid":"lkxZC7WEOIs=","x5c":["MIICoTCCAkegAwIBAgIUXyW8Eb8M4PiKkdr7IOs76K1KvgQwCgYIKoZIzj0EAwIwbTELMAkGA1UEBhMCWEwxEzARBgNVBAgMClRlc3QgU3RhdGUxEzARBgNVBAcMCkNhbGlmb3JuaWExDzANBgNVBAoMBkNyZWF0ZTEMMAoGA1UECwwDUiZEMRUwEwYDVQQDDAxOYXRpb25YQ19UTlAwHhcNMjUwOTE1MTYzNTMwWhcNMjcwOTE1MTYzNTMwWjBtMQswCQYDVQQGEwJYTDETMBEGA1UECAwKVGVzdCBTdGF0ZTETMBEGA1UEBwwKQ2FsaWZvcm5pYTEPMA0GA1UECgwGQ3JlYXRlMQwwCgYDVQQLDANSJkQxFTATBgNVBAMMDE5hdGlvblhDX1ROUDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFgLQ2NpmIdaotfGiR0DRQ3OXWj6nTS0aqUphzXVjCi6A+kULLvX3qB/1bDLnrvMSvpVqzzSq0GocSA+4f2OWxKjgcQwgcEwDgYDVR0PAQH/BAQDAgeAMB0GA1UdDgQWBBQlEhNfCSe2r4WafE/EyFSY0TTAIDAfBgNVHSMEGDAWgBQ6ucEi0XUzbXD4njquKtEXAtxYnzA9BgNVHR8ENjA0MDKgMKAuhixodHRwOi8vY3JsLmV4YW1wbGVkb21haW4uZXhhbXBsZS9DUkwvU0NBLmNybDAwBgNVHSUEKTAnBgsrBgEEAY43j2UBAQYLKwYBBAGON49lAQIGCysGAQQBjjePZQEDMAoGCCqGSM49BAMCA0gAMEUCIQCrOl1QmsOhzAXjYoTj26yVogte53eNqOKc6qrbtfZIGwIgH+lKLGJTo7wlyutgQ2EF49Bj7UFu3w9vP5Ri/Hp0voU=","MIICIDCCAcegAwIBAgIUeo8sCjTu/O8lEw5+msfG6Ss/qmAwCgYIKoZIzj0EAwIwbTELMAkGA1UEBhMCWEwxEzARBgNVBAgMClRlc3QgU3RhdGUxEzARBgNVBAcMCkNhbGlmb3JuaWExDzANBgNVBAoMBkNyZWF0ZTEMMAoGA1UECwwDUiZEMRUwEwYDVQQDDAxOYXRpb25YQ19UTlAwHhcNMjUwOTA1MjIyODExWhcNMjkwOTA1MjIyODExWjBtMQswCQYDVQQGEwJYTDETMBEGA1UECAwKVGVzdCBTdGF0ZTETMBEGA1UEBwwKQ2FsaWZvcm5pYTEPMA0GA1UECgwGQ3JlYXRlMQwwCgYDVQQLDANSJkQxFTATBgNVBAMMDE5hdGlvblhDX1ROUDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGyu+Fiohg8APhNR8M0ES2qC0bMXLQb8QCoAakFJ0yubhJku+Q1hJE1uXIJo1JMMMSqhWkH6ZLaroQgCrXEfeXqjRTBDMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBQ6ucEi0XUzbXD4njquKtEXAtxYnzAKBggqhkjOPQQDAgNHADBEAiAYInGL6MNXhsxaHULBN7qoGdZU0fCUcU/Ga015QzDH6gIged0zuy/RlSqRb8BGgMwmJ9m/8WT82FpG2obN/QxPMGI="],"crv":"P-256","x":"WAtDY2mYh1qi18aJHQNFDc5daPqdNLRqpSmHNdWMKLo","y":"A-kULLvX3qB_1bDLnrvMSvpVqzzSq0GocSA-4f2OWxI"},"domain":"PH4H","participant":"XL","keyusage":"DSC"}],"proof":{"type":"JsonWebSignature2020","created":"2026-01-04T06:00:26Z","nonce":"quBNC4BLGAiuULyynAPMhMt1O0pzIH1Y","proofPurpose":"assertionMethod","verificationMethod":"did:web:raw.githubusercontent.com:WorldHealthOrganization:tng-participants-dev:main:WHO:signing:DID","jws":"eyJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdLCJhbGciOiJFUzI1NiJ9..MEQCIEe0i0KnlvG41pG8XVDUfo7-1nWPgCgKndj1Snn8hGPyAiApHO4bRW0CcuAtK7Q8LE5WuRt_HHIKBvRjvEfRhp59JQ"}}

=== WorldHealthOrganization/tng-cdn-dev/v2/trustlist/PH4H/XG/did.json
{"@context":["https://www.w3.org/ns/did/v1","https://w3id.org/security/suites/jws-2020/v1","https://worldhealthorganization.github.io/smart-trust/tng-additional-context/v1"],"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H:XG","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H","verificationMethod":[{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H:XG:SCA#VsqB8MP0/ho=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H","publicKeyJwk":{"kty":"EC","kid":"VsqB8MP0/ho=","x5c":["MIICEzCCAbmgAwIBAgIUMYEsHXBQn1MZ22ld5Xs1TR93GiQwCgYIKoZIzj0EAwIwZjELMAkGA1UEBhMCWEcxEzARBgNVBAgMClRlc3QgU3RhdGUxDzANBgNVBAcMBkdlbmV2YTEMMAoGA1UECgwDV0hPMQwwCgYDVQQLDANSJkQxFTATBgNVBAMMDE5hdGlvblhDX1ROUDAeFw0yNTA5MjUxMjU4MDdaFw0yOTA5MjUxMjU4MDdaMGYxCzAJBgNVBAYTAlhHMRMwEQYDVQQIDApUZXN0IFN0YXRlMQ8wDQYDVQQHDAZHZW5ldmExDDAKBgNVBAoMA1dITzEMMAoGA1UECwwDUiZEMRUwEwYDVQQDDAxOYXRpb25YQ19UTlAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASXYPuWZvccoo4sD6YZqBz96uWHfO4f1BDmysfpKaSpDfbLclrUJZuWJ1vXdoqG6W2PIqJoMnVSld6NA14SzYTuo0UwQzASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQU/1pyYI7/Gk0EznIFqjiR0LyCGwYwCgYIKoZIzj0EAwIDSAAwRQIhANza+6XcacBLL3T459jcIIihdDXm7pD9vfqEu3hrUB1GAiB8Y4oCzO+A75qmY42PrvIMaOVyJOv/cqV21sqcKbTi3A=="],"crv":"P-256","x":"AJdg-5Zm9xyijiwPphmoHP3q5Yd87h_UEObKx-kppKkN","y":"APbLclrUJZuWJ1vXdoqG6W2PIqJoMnVSld6NA14SzYTu"},"domain":"PH4H","participant":"XG","keyusage":"SCA"}],"proof":{"type":"JsonWebSignature2020","created":"2026-01-04T06:00:14Z","nonce":"q7K1caYM7rEGDHnB2D9QFeTotcf4FMWQ","proofPurpose":"assertionMethod","verificationMethod":"did:web:raw.githubusercontent.com:WorldHealthOrganization:tng-participants-dev:main:WHO:signing:DID","jws":"eyJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdLCJhbGciOiJFUzI1NiJ9..MEUCIBkORhWe6NxUcb6C4NwfN8VSpRJdM7JWkOoLbBdvXkr8AiEAgKAn6XL5IWWveclxpGyxZEn0Qf6tztTwblInTMQVnKE"}}

=== WorldHealthOrganization/tng-cdn-dev/v2/trustlist/PH4H/XE/DSC/did.json
{"@context":["https://www.w3.org/ns/did/v1","https://w3id.org/security/suites/jws-2020/v1"],"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H:XE:DSC","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H:XE","verificationMethod":[{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H:XE:DSC#8HaP4GVaX8E=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H:XE","publicKeyJwk":{"kty":"EC","kid":"8HaP4GVaX8E=","x5c":["MIICfzCCAiWgAwIBAgIUAZr4jgOv7HbiKX8YoCY0RIkvXokwCgYIKoZIzj0EAwIwbzELMAkGA1UEBhMCWEUxETAPBgNVBAgMCFhFIFN0YXRlMRQwEgYDVQQHDAtYRSBMb2NhbGl0eTENMAsGA1UECgwEQ0VOUzENMAsGA1UECwwEQ0VOUzEZMBcGA1UEAwwQTmF0aW9uWEFfVE5QX1NDQTAeFw0yNDEwMTExOTMwMzdaFw0yNjEwMTExOTMwMzdaMGMxCzAJBgNVBAYTAlhFMREwDwYDVQQIDAhYRSBTdGF0ZTEUMBIGA1UEBwwLWEUgTG9jYWxpdHkxDTALBgNVBAoMBENFTlMxDTALBgNVBAsMBENFTlMxDTALBgNVBAMMBENFTlMwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATVCRn4w+C3WE8yKkga69YJP4OQO2v8TT1tLueMLMOSxtxWZTlhPulFa2bW9cx+Ni39oAAmQVmCccOrswKkW1Oyo4GqMIGnMA4GA1UdDwEB/wQEAwIHgDAdBgNVHQ4EFgQUcinYI4JtYmQr2NelBiSJe6O0c2MwHwYDVR0jBBgwFoAUP1ezfs8VWVnkWmrJfIDme9mwvKkwPQYDVR0fBDYwNDAyoDCgLoYsaHR0cDovL2NybC5leGFtcGxlZG9tYWluLmV4YW1wbGUvQ1JML1NDQS5jcmwwFgYDVR0lBA8wDQYLKwYBBAGON49lAQEwCgYIKoZIzj0EAwIDSAAwRQIhAIoJVT+iTSULRQq7dSeKv7/qPiccFSGpkfqRzd1wDK6QAiBcxAVC4X7GeyvNZuPECtSOpc3rIMg3MsqlC9yYZk6k6g==","MIICJDCCAcugAwIBAgIUThwf+0WcLDKLfUo2xCcXUJO+3FUwCgYIKoZIzj0EAwIwbzELMAkGA1UEBhMCWEUxETAPBgNVBAgMCFhFIFN0YXRlMRQwEgYDVQQHDAtYRSBMb2NhbGl0eTENMAsGA1UECgwEQ0VOUzENMAsGA1UECwwEQ0VOUzEZMBcGA1UEAwwQTmF0aW9uWEFfVE5QX1NDQTAeFw0yNDA5MjkxODI3NDNaFw0yODA5MjkxODI3NDNaMG8xCzAJBgNVBAYTAlhFMREwDwYDVQQIDAhYRSBTdGF0ZTEUMBIGA1UEBwwLWEUgTG9jYWxpdHkxDTALBgNVBAoMBENFTlMxDTALBgNVBAsMBENFTlMxGTAXBgNVBAMMEE5hdGlvblhBX1ROUF9TQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAS2KU9DbyE5nH6g0SOcgIpY9hYshnShK3dB6IrE/ZIwVnxDkvK+tpwMsrXl8Zhlsa+hPbaMPpAas51E2burUChbo0UwQzASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUP1ezfs8VWVnkWmrJfIDme9mwvKkwCgYIKoZIzj0EAwIDRwAwRAIgb1MUndcyguayll4rEmrZNFH6b8TnqDlxKSxhdLAfYM8CIBxQ5ds0nvEGdtSscs4GmdzGQ/S15C3bCMDMlpsPloBO"],"crv":"P-256","x":"ANUJGfjD4LdYTzIqSBrr1gk_g5A7a_xNPW0u54wsw5LG","y":"ANxWZTlhPulFa2bW9cx-Ni39oAAmQVmCccOrswKkW1Oy"},"domain":"PH4H","participant":"XE","keyusage":"DSC"}],"proof":{"type":"JsonWebSignature2020","created":"2025-07-15T00:00:15Z","nonce":"bXnIH4aK2TUDjQJiUeAVl73c5gsOehqQ","proofPurpose":"assertionMethod","verificationMethod":"did:web:raw.githubusercontent.com:WorldHealthOrganization:tng-participants-dev:main:WHO:signing:DID","jws":"eyJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdLCJhbGciOiJFUzI1NiJ9..MEQCIBx0omXo_Ds1E-XOivQ_LmJq2q5xDiDr3cSsmPCPaKUgAiARyu1yuANmySAYuJmCtXoCG4S-CEYwdURcJuYdsjG-2w"}}
