=== WorldHealthOrganization/tng-cdn-dev/schema/did-trustlist-syntax-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/WorldHealthOrganization/tng-cdn-dev/refs/heads/main/schema/did-trustlist-syntax-schema.json",
  "title": "DID Document Syntax Schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "@context": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "id": {
      "type": "string"
    },
    "controller": {
      "type": "string"
    },
    "verificationMethod": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "controller": {
            "type": "string"
          },

          "publicKeyJwk": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "kty": { "type": "string" },
              "kid": { "type": "string" },
              "x5c": {
                "type": "array",
                "items": { "type": "string" }
              },
              "crv": { "type": "string" },
              "x": { "type": "string" },
              "y": { "type": "string" },
              "e": { "type": "string" },
              "n": { "type": "string" }
            },
            "required": ["kty", "kid", "x5c"]
          },

          "domain": {
            "type": "string"
          },
          "participant": {
            "type": "string"
          },
          "keyusage": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "type",
          "controller",
          "publicKeyJwk",
          "domain",
          "participant",
          "keyusage"
        ]
      }
    },

    "proof": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": { "type": "string" },
        "created": { "type": "string" },
        "nonce": { "type": "string" },
        "proofPurpose": { "type": "string" },
        "verificationMethod": { "type": "string" },
        "jws": { "type": "string" }
      },
      "required": [
        "type",
        "created",
        "nonce",
        "proofPurpose",
        "verificationMethod",
        "jws"
      ]
    }
  },
  "required": [
    "@context",
    "id",
    "controller",
    "verificationMethod",
    "proof"
  ]
}

=== WorldHealthOrganization/tng-cdn-dev/v2/trustlist/-/XL/SCA/did.json
{"@context":["https://www.w3.org/ns/did/v1","https://w3id.org/security/suites/jws-2020/v1","https://worldhealthorganization.github.io/smart-trust/tng-additional-context/v1"],"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:-:XL:SCA","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:-:XL","verificationMethod":[{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:-:XL:SCA#2RIYRNJvPBg=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:-:XL","publicKeyJwk":{"kty":"EC","kid":"2RIYRNJvPBg=","x5c":["MIICFTCCAbugAwIBAgIUN2LeFtoIJ9RnfWbtm2KmavrqVH8wCgYIKoZIzj0EAwIwZzELMAkGA1UEBhMCWEwxCzAJBgNVBAgMAk1UMREwDwYDVQQHDAhTQU5USUFHTzEPMA0GA1UECgwGQ1JFQVRFMQwwCgYDVQQLDANSJkQxGTAXBgNVBAMMEE5hdGlvblhMX1ROUF9TQ0EwHhcNMjMwOTI4MTczMDU0WhcNMjcwOTI4MTczMDU0WjBnMQswCQYDVQQGEwJYTDELMAkGA1UECAwCTVQxETAPBgNVBAcMCFNBTlRJQUdPMQ8wDQYDVQQKDAZDUkVBVEUxDDAKBgNVBAsMA1ImRDEZMBcGA1UEAwwQTmF0aW9uWExfVE5QX1NDQTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABADa29gT9IMfh6XgAjNUFA/ckQEpjkHFCm3rAK47gNZ2nNIqutk15wILxLT3Zf6aMNwPcEn38iFaJaqKSQr663+jRTBDMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBQOLQgcF/crtl6LuK9tYr650XygFjAKBggqhkjOPQQDAgNIADBFAiEAj2JHlg2ds+N5GRum3X1p6wUDppwUJjqtJRS/xxzU0fYCIFb56xpwL/nVQ+2/xyOlN9aVS+Gbq8u5+r1HePKGeMEJ"],"crv":"P-256","x":"ANrb2BP0gx-HpeACM1QUD9yRASmOQcUKbesArjuA1nY","y":"AJzSKrrZNecCC8S092X-mjDcD3BJ9_IhWiWqikkK-ut_"},"domain":"DCC","participant":"XL","keyusage":"SCA"},{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:-:XL:SCA#3wiKBCaFuok=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:-:XL","publicKeyJwk":{"kty":"EC","kid":"3wiKBCaFuok=","x5c":["MIICFTCCAbugAwIBAgIUZg3GCdgTYDbAORHyethAud82ETAwCgYIKoZIzj0EAwIwZzELMAkGA1UEBhMCWEwxCzAJBgNVBAgMAk1UMREwDwYDVQQHDAhTQU5USUFHTzEPMA0GA1UECgwGQ1JFQVRFMQwwCgYDVQQLDANSJkQxGTAXBgNVBAMMEE5hdGlvblhMX1ROUF9TQ0EwHhcNMjMxMDA0MTUyMTI3WhcNMjcxMDA0MTUyMTI3WjBnMQswCQYDVQQGEwJYTDELMAkGA1UECAwCTVQxETAPBgNVBAcMCFNBTlRJQUdPMQ8wDQYDVQQKDAZDUkVBVEUxDDAKBgNVBAsMA1ImRDEZMBcGA1UEAwwQTmF0aW9uWExfVE5QX1NDQTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABOUht3wSLNl4Ae1/wRUfVY1CTKrOog+vuIyrIUOdCcIumeAz8AckJdfVTN5+sVcGkw1T8kQFMNaf5lCv8QH6jXWjRTBDMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBQmHPdh8sTGTj8CpqhvKV/RXTwIujAKBggqhkjOPQQDAgNIADBFAiAOsxW3y3KitIQUu3NnKVL79Hc4wuAESSfDN2H6NGtCxQIhAKAmub3n49gFLDFcpc4rOX9GgUGvf5XEbzuXtMADgsll"],"crv":"P-256","x":"AOUht3wSLNl4Ae1_wRUfVY1CTKrOog-vuIyrIUOdCcIu","y":"AJngM_AHJCXX1UzefrFXBpMNU_JEBTDWn-ZQr_EB-o11"},"domain":"RACSEL-DDVC","participant":"XL","keyusage":"SCA"},{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:-:XL:SCA#8nAX0I7m7A0=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:-:XL","publicKeyJwk":{"kty":"EC","kid":"8nAX0I7m7A0=","x5c":["MIICDDCCAbOgAwIBAgIUWizt1UMJI5R+p7d99hVV+HCbLAUwCgYIKoZIzj0EAwIwYzELMAkGA1UEBhMCWEwxCzAJBgNVBAgMAk1UMREwDwYDVQQHDAhTYW50aWFnbzEQMA4GA1UECgwHTEFDUGFzczEQMA4GA1UECwwHTEFDUGFzczEQMA4GA1UEAwwHTEFDUGFzczAeFw0yMzA5MDUxMjI5NTNaFw0yNzA5MDUxMjI5NTNaMGMxCzAJBgNVBAYTAlhMMQswCQYDVQQIDAJNVDERMA8GA1UEBwwIU2FudGlhZ28xEDAOBgNVBAoMB0xBQ1Bhc3MxEDAOBgNVBAsMB0xBQ1Bhc3MxEDAOBgNVBAMMB0xBQ1Bhc3MwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAS6oX06i1IFeRR/G2yUtVWFxaknWsZBFGh7rsEiYzRYKh4Q4+kWbXTNdlnCBWWeg2pkTtn8yY8lBiZzE3VOdIzAo0UwQzASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQU/ElE7e3KGwtsuerSyFOrod1UxDkwCgYIKoZIzj0EAwIDRwAwRAIgEvuyBlQTNHXo+mzXWiFf2dzrU27ZovslezGL+2dpGjECIC8qbgvYpF6Smo4nBC+tzU2zxiOeRewqfpzAQqEvo4mF"],"crv":"P-256","x":"ALqhfTqLUgV5FH8bbJS1VYXFqSdaxkEUaHuuwSJjNFgq","y":"HhDj6RZtdM12WcIFZZ6DamRO2fzJjyUGJnMTdU50jMA"},"domain":"DCC","participant":"XL","keyusage":"SCA"},{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:-:XL:SCA#MD93Io4g9GE=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:-:XL","publicKeyJwk":{"kty":"EC","kid":"MD93Io4g9GE=","x5c":["MIICIDCCAcegAwIBAgIUeo8sCjTu/O8lEw5+msfG6Ss/qmAwCgYIKoZIzj0EAwIwbTELMAkGA1UEBhMCWEwxEzARBgNVBAgMClRlc3QgU3RhdGUxEzARBgNVBAcMCkNhbGlmb3JuaWExDzANBgNVBAoMBkNyZWF0ZTEMMAoGA1UECwwDUiZEMRUwEwYDVQQDDAxOYXRpb25YQ19UTlAwHhcNMjUwOTA1MjIyODExWhcNMjkwOTA1MjIyODExWjBtMQswCQYDVQQGEwJYTDETMBEGA1UECAwKVGVzdCBTdGF0ZTETMBEGA1UEBwwKQ2FsaWZvcm5pYTEPMA0GA1UECgwGQ3JlYXRlMQwwCgYDVQQLDANSJkQxFTATBgNVBAMMDE5hdGlvblhDX1ROUDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGyu+Fiohg8APhNR8M0ES2qC0bMXLQb8QCoAakFJ0yubhJku+Q1hJE1uXIJo1JMMMSqhWkH6ZLaroQgCrXEfeXqjRTBDMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBQ6ucEi0XUzbXD4njquKtEXAtxYnzAKBggqhkjOPQQDAgNHADBEAiAYInGL6MNXhsxaHULBN7qoGdZU0fCUcU/Ga015QzDH6gIged0zuy/RlSqRb8BGgMwmJ9m/8WT82FpG2obN/QxPMGI="],"crv":"P-256","x":"bK74WKiGDwA-E1HwzQRLaoLRsxctBvxAKgBqQUnTK5s","y":"AISZLvkNYSRNblyCaNSTDDEqoVpB-mS2q6EIAq1xH3l6"},"domain":"PH4H","participant":"XL","keyusage":"SCA"},{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:-:XL:SCA#hRJFN+daQrI=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:-:XL","publicKeyJwk":{"kty":"EC","kid":"hRJFN+daQrI=","x5c":["MIICAjCCAaegAwIBAgIUKF4lTmfdzK4G2N70l0ZsuqwnvCUwCgYIKoZIzj0EAwIwXTELMAkGA1UEBhMCWEwxCzAJBgNVBAgMAk1UMREwDwYDVQQHDAhTYW50aWFnbzEPMA0GA1UECgwGQ3JlYXRlMQwwCgYDVQQLDANSJkQxDzANBgNVBAMMBkNyZWF0ZTAeFw0yNDA5MTAyMDUxMjhaFw0yODA5MTAyMDUxMjhaMF0xCzAJBgNVBAYTAlhMMQswCQYDVQQIDAJNVDERMA8GA1UEBwwIU2FudGlhZ28xDzANBgNVBAoMBkNyZWF0ZTEMMAoGA1UECwwDUiZEMQ8wDQYDVQQDDAZDcmVhdGUwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATwTvXHsCOZVe8cux/7YJF1Z5fTQJBWjiOlosaXWxi+72l4i8PECtFyEV+s1vk8ynZ8BSlEanXA7yWnzXf1mZsHo0UwQzASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUltU4J1etuXVuGvSffa+h2q0xeGowCgYIKoZIzj0EAwIDSQAwRgIhAMbyCD/0VopFYhpYdxUWomzSwlH5iqBlgym9DmsTeUvwAiEA3CyeKGAibv5NIj7EkGazFTP+gvqAvPAqViVNty9TJWo="],"crv":"P-256","x":"APBO9cewI5lV7xy7H_tgkXVnl9NAkFaOI6WixpdbGL7v","y":"aXiLw8QK0XIRX6zW-TzKdnwFKURqdcDvJafNd_WZmwc"},"domain":"PH4H","participant":"XL","keyusage":"SCA"}],"proof":{"type":"JsonWebSignature2020","created":"2026-01-04T06:00:29Z","nonce":"xOyHVIU4A482TyNflMpPf5W4pvGgM5jK","proofPurpose":"assertionMethod","verificationMethod":"did:web:raw.githubusercontent.com:WorldHealthOrganization:tng-participants-dev:main:WHO:signing:DID","jws":"eyJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdLCJhbGciOiJFUzI1NiJ9..MEUCIEQzahWS5kFJJLUdHHlB55WTXAV_O-ewBbIoc3wVp9HbAiEAu7kmM-7lKRvWZhwFefCxD32c-audnKjD0KtgLpXdvS8"}}

=== WorldHealthOrganization/tng-cdn-dev/v2/trustlist/PH4H/XL/did.json
{"@context":["https://www.w3.org/ns/did/v1","https://w3id.org/security/suites/jws-2020/v1","https://worldhealthorganization.github.io/smart-trust/tng-additional-context/v1"],"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H:XL","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H","verificationMethod":[{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H:XL:SCA#MD93Io4g9GE=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H","publicKeyJwk":{"kty":"EC","kid":"MD93Io4g9GE=","x5c":["MIICIDCCAcegAwIBAgIUeo8sCjTu/O8lEw5+msfG6Ss/qmAwCgYIKoZIzj0EAwIwbTELMAkGA1UEBhMCWEwxEzARBgNVBAgMClRlc3QgU3RhdGUxEzARBgNVBAcMCkNhbGlmb3JuaWExDzANBgNVBAoMBkNyZWF0ZTEMMAoGA1UECwwDUiZEMRUwEwYDVQQDDAxOYXRpb25YQ19UTlAwHhcNMjUwOTA1MjIyODExWhcNMjkwOTA1MjIyODExWjBtMQswCQYDVQQGEwJYTDETMBEGA1UECAwKVGVzdCBTdGF0ZTETMBEGA1UEBwwKQ2FsaWZvcm5pYTEPMA0GA1UECgwGQ3JlYXRlMQwwCgYDVQQLDANSJkQxFTATBgNVBAMMDE5hdGlvblhDX1ROUDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGyu+Fiohg8APhNR8M0ES2qC0bMXLQb8QCoAakFJ0yubhJku+Q1hJE1uXIJo1JMMMSqhWkH6ZLaroQgCrXEfeXqjRTBDMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBQ6ucEi0XUzbXD4njquKtEXAtxYnzAKBggqhkjOPQQDAgNHADBEAiAYInGL6MNXhsxaHULBN7qoGdZU0fCUcU/Ga015QzDH6gIged0zuy/RlSqRb8BGgMwmJ9m/8WT82FpG2obN/QxPMGI="],"crv":"P-256","x":"bK74WKiGDwA-E1HwzQRLaoLRsxctBvxAKgBqQUnTK5s","y":"AISZLvkNYSRNblyCaNSTDDEqoVpB-mS2q6EIAq1xH3l6"},"domain":"PH4H","participant":"XL","keyusage":"SCA"},{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H:XL:SCA#hRJFN+daQrI=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H","publicKeyJwk":{"kty":"EC","kid":"hRJFN+daQrI=","x5c":["MIICAjCCAaegAwIBAgIUKF4lTmfdzK4G2N70l0ZsuqwnvCUwCgYIKoZIzj0EAwIwXTELMAkGA1UEBhMCWEwxCzAJBgNVBAgMAk1UMREwDwYDVQQHDAhTYW50aWFnbzEPMA0GA1UECgwGQ3JlYXRlMQwwCgYDVQQLDANSJkQxDzANBgNVBAMMBkNyZWF0ZTAeFw0yNDA5MTAyMDUxMjhaFw0yODA5MTAyMDUxMjhaMF0xCzAJBgNVBAYTAlhMMQswCQYDVQQIDAJNVDERMA8GA1UEBwwIU2FudGlhZ28xDzANBgNVBAoMBkNyZWF0ZTEMMAoGA1UECwwDUiZEMQ8wDQYDVQQDDAZDcmVhdGUwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATwTvXHsCOZVe8cux/7YJF1Z5fTQJBWjiOlosaXWxi+72l4i8PECtFyEV+s1vk8ynZ8BSlEanXA7yWnzXf1mZsHo0UwQzASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUltU4J1etuXVuGvSffa+h2q0xeGowCgYIKoZIzj0EAwIDSQAwRgIhAMbyCD/0VopFYhpYdxUWomzSwlH5iqBlgym9DmsTeUvwAiEA3CyeKGAibv5NIj7EkGazFTP+gvqAvPAqViVNty9TJWo="],"crv":"P-256","x":"APBO9cewI5lV7xy7H_tgkXVnl9NAkFaOI6WixpdbGL7v","y":"aXiLw8QK0XIRX6zW-TzKdnwFKURqdcDvJafNd_WZmwc"},"domain":"PH4H","participant":"XL","keyusage":"SCA"},{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H:XL:DSC#lkxZC7WEOIs=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:PH4H","publicKeyJwk":{"kty":"EC","kid":"lkxZC7WEOIs=","x5c":["MIICoTCCAkegAwIBAgIUXyW8Eb8M4PiKkdr7IOs76K1KvgQwCgYIKoZIzj0EAwIwbTELMAkGA1UEBhMCWEwxEzARBgNVBAgMClRlc3QgU3RhdGUxEzARBgNVBAcMCkNhbGlmb3JuaWExDzANBgNVBAoMBkNyZWF0ZTEMMAoGA1UECwwDUiZEMRUwEwYDVQQDDAxOYXRpb25YQ19UTlAwHhcNMjUwOTE1MTYzNTMwWhcNMjcwOTE1MTYzNTMwWjBtMQswCQYDVQQGEwJYTDETMBEGA1UECAwKVGVzdCBTdGF0ZTETMBEGA1UEBwwKQ2FsaWZvcm5pYTEPMA0GA1UECgwGQ3JlYXRlMQwwCgYDVQQLDANSJkQxFTATBgNVBAMMDE5hdGlvblhDX1ROUDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFgLQ2NpmIdaotfGiR0DRQ3OXWj6nTS0aqUphzXVjCi6A+kULLvX3qB/1bDLnrvMSvpVqzzSq0GocSA+4f2OWxKjgcQwgcEwDgYDVR0PAQH/BAQDAgeAMB0GA1UdDgQWBBQlEhNfCSe2r4WafE/EyFSY0TTAIDAfBgNVHSMEGDAWgBQ6ucEi0XUzbXD4njquKtEXAtxYnzA9BgNVHR8ENjA0MDKgMKAuhixodHRwOi8vY3JsLmV4YW1wbGVkb21haW4uZXhhbXBsZS9DUkwvU0NBLmNybDAwBgNVHSUEKTAnBgsrBgEEAY43j2UBAQYLKwYBBAGON49lAQIGCysGAQQBjjePZQEDMAoGCCqGSM49BAMCA0gAMEUCIQCrOl1QmsOhzAXjYoTj26yVogte53eNqOKc6qrbtfZIGwIgH+lKLGJTo7wlyutgQ2EF49Bj7UFu3w9vP5Ri/Hp0voU=","MIICIDCCAcegAwIBAgIUeo8sCjTu/O8lEw5+msfG6Ss/qmAwCgYIKoZIzj0EAwIwbTELMAkGA1UEBhMCWEwxEzARBgNVBAgMClRlc3QgU3RhdGUxEzARBgNVBAcMCkNhbGlmb3JuaWExDzANBgNVBAoMBkNyZWF0ZTEMMAoGA1UECwwDUiZEMRUwEwYDVQQDDAxOYXRpb25YQ19UTlAwHhcNMjUwOTA1MjIyODExWhcNMjkwOTA1MjIyODExWjBtMQswCQYDVQQGEwJYTDETMBEGA1UECAwKVGVzdCBTdGF0ZTETMBEGA1UEBwwKQ2FsaWZvcm5pYTEPMA0GA1UECgwGQ3JlYXRlMQwwCgYDVQQLDANSJkQxFTATBgNVBAMMDE5hdGlvblhDX1ROUDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGyu+Fiohg8APhNR8M0ES2qC0bMXLQb8QCoAakFJ0yubhJku+Q1hJE1uXIJo1JMMMSqhWkH6ZLaroQgCrXEfeXqjRTBDMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBQ6ucEi0XUzbXD4njquKtEXAtxYnzAKBggqhkjOPQQDAgNHADBEAiAYInGL6MNXhsxaHULBN7qoGdZU0fCUcU/Ga015QzDH6gIged0zuy/RlSqRb8BGgMwmJ9m/8WT82FpG2obN/QxPMGI="],"crv":"P-256","x":"WAtDY2mYh1qi18aJHQNFDc5daPqdNLRqpSmHNdWMKLo","y":"A-kULLvX3qB_1bDLnrvMSvpVqzzSq0GocSA-4f2OWxI"},"domain":"PH4H","participant":"XL","keyusage":"DSC"}],"proof":{"type":"JsonWebSignature2020","created":"2026-01-04T06:00:14Z","nonce":"R7PcJBL9m7SrhHBkcEWQrGJxTdeR5U5d","proofPurpose":"assertionMethod","verificationMethod":"did:web:raw.githubusercontent.com:WorldHealthOrganization:tng-participants-dev:main:WHO:signing:DID","jws":"eyJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdLCJhbGciOiJFUzI1NiJ9..MEUCICV1hdQYUTa4lFq-lwylbTxXPZeKDjJ4x9n1uSH09AVIAiEAhYGR5qnGPw4UoicaXjYpbKCdyNNmJyoeeywp63sPGT8"}}

=== WorldHealthOrganization/tng-cdn-dev/v2/trustlist/DCC/XV/DSC/did.json
{"@context":["https://www.w3.org/ns/did/v1","https://w3id.org/security/suites/jws-2020/v1","https://worldhealthorganization.github.io/smart-trust/tng-additional-context/v1"],"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:DCC:XV:DSC","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:DCC:XV","verificationMethod":[{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:DCC:XV:DSC#9hJbmczFOn8=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:DCC:XV","publicKeyJwk":{"kty":"EC","kid":"9hJbmczFOn8=","x5c":["MIICkDCCAjWgAwIBAgIUVVA2TzUxgDj2aXWWWgQnxx6xMBUwCgYIKoZIzj0EAwQwZDELMAkGA1UEBhMCWFYxEzARBgNVBAgMClRlc3QgU3RhdGUxDTALBgNVBAcMBFRFU1QxDDAKBgNVBAoMA1dITzEMMAoGA1UECwwDUiZEMRUwEwYDVQQDDAxOYXRpb25YVl9UTlAwHhcNMjUwOTAxMTA1NzI2WhcNMjcwOTAxMTA1NzI2WjBkMQswCQYDVQQGEwJYVjETMBEGA1UECAwKVGVzdCBTdGF0ZTENMAsGA1UEBwwEVEVTVDEMMAoGA1UECgwDV0hPMQwwCgYDVQQLDANSJkQxFTATBgNVBAMMDE5hdGlvblhWX1ROUDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDV4lMctzTa/lV06vJ+TRa5s1vl2fvPTvXSv2UftPlICQKxpYfc4lag2fwNS2n8FH73WcEE9szy6hqpoL9mAdY+jgcQwgcEwDgYDVR0PAQH/BAQDAgeAMB0GA1UdDgQWBBTfWFJyyJ/ARX72OxnBSO+rTL4Q8DAfBgNVHSMEGDAWgBShd9Ym72gdGfWqqXd7Z4GP0wEKrDA9BgNVHR8ENjA0MDKgMKAuhixodHRwOi8vY3JsLmV4YW1wbGVkb21haW4uZXhhbXBsZS9DUkwvU0NBLmNybDAwBgNVHSUEKTAnBgsrBgEEAY43j2UBAQYLKwYBBAGON49lAQIGCysGAQQBjjePZQEDMAoGCCqGSM49BAMEA0kAMEYCIQChgymN7LD1apWdO9I4wQz+Wu5nwH/g/ztvyxTslCxYuAIhAKZigtiskuZksJJpWVh5EnBvA1AQAK4sV0mUg8pN1GAE","MIICDzCCAbWgAwIBAgIUByPWCqZ1JVl/kRq4q5kshH5Ik+gwCgYIKoZIzj0EAwQwZDELMAkGA1UEBhMCWFYxEzARBgNVBAgMClRlc3QgU3RhdGUxDTALBgNVBAcMBFRFU1QxDDAKBgNVBAoMA1dITzEMMAoGA1UECwwDUiZEMRUwEwYDVQQDDAxOYXRpb25YVl9UTlAwHhcNMjUwOTAxMDk1MzU3WhcNMjkwOTAxMDk1MzU3WjBkMQswCQYDVQQGEwJYVjETMBEGA1UECAwKVGVzdCBTdGF0ZTENMAsGA1UEBwwEVEVTVDEMMAoGA1UECgwDV0hPMQwwCgYDVQQLDANSJkQxFTATBgNVBAMMDE5hdGlvblhWX1ROUDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDopop2wk9cKLqZBkgEPw0HBgr3p6yUmAayCrIXut83ScLMd45HfxU1xcOuS33ZumO47xapf2UDVgVinyAdm5eGjRTBDMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBShd9Ym72gdGfWqqXd7Z4GP0wEKrDAKBggqhkjOPQQDBANIADBFAiBjQC0cxPM5KLzDUtQsoLFbqzB6mLu9qU36Dpq+5dCF1gIhAPLqMwuqh41kgA1SzSoV7sovSwxHvp0rxhTD5pfGrm2K"],"crv":"P-256","x":"NXiUxy3NNr-VXTq8n5NFrmzW-XZ-89O9dK_ZR-0-UgI","y":"QKxpYfc4lag2fwNS2n8FH73WcEE9szy6hqpoL9mAdY8"},"domain":"DCC","participant":"XV","keyusage":"DSC"},{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:DCC:XV:DSC#nPsnRUYfcgc=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:DCC:XV","publicKeyJwk":{"kty":"EC","kid":"nPsnRUYfcgc=","x5c":["MIIChTCCAiqgAwIBAgIUP2WstZcKc0lNL2mGYGE45vBDBVIwCgYIKoZIzj0EAwIwWjELMAkGA1UEBhMCWFYxDTALBgNVBAgMBHRlc3QxDjAMBgNVBAcMBUluZGlhMQwwCgYDVQQKDANXSE8xEDAOBgNVBAsMB09wc3RlYW0xDDAKBgNVBAMMA1NDQTAeFw0yNTEwMjAxMTMxMDBaFw0yNzEwMjAxMTMyMDBaMGMxCzAJBgNVBAYTAlhWMQ0wCwYDVQQIDAR0ZXN0MQ4wDAYDVQQHDAVJTkRJQTEMMAoGA1UECgwDV0hPMRAwDgYDVQQLDAdvcHN0ZWFtMRUwEwYDVQQDDAxOYXRpb25YVl9UTlAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAT7a64eYQ/R69TQZI5lp8IqSBtVtCRikEntpCQaRlvpTpItI3ON25bI15nTLu1u86RWf5J4y2QUFHY4hSIXIgJjo4HEMIHBMB0GA1UdDgQWBBS7Qcw2j6gsFlr5ITDGMBZS+GmYsTAfBgNVHSMEGDAWgBTBIjBO1xkolAaASgmXDwpSLHd5/zAOBgNVHQ8BAf8EBAMCB4AwMAYDVR0lBCkwJwYLKwYBBAGON49lAQEGCysGAQQBjjePZQECBgsrBgEEAY43j2UBAzA9BgNVHR8ENjA0MDKgMKAuhixodHRwOi8vY3JsLmV4YW1wbGVkb21haW4uZXhhbXBsZS9DUkwvU0NBLmNybDAKBggqhkjOPQQDAgNJADBGAiEAz+Z3CJoHNSc10s2SNKT5yAUZsohw9i4CA1GDQRr3KukCIQD4sEZDEZEN1NmbmbOrOmGZtAQVvp683AtDe/6JOzaZzQ==","MIIB/DCCAaGgAwIBAgIUTPIJMvNw8eS1OhG2tQ+W44LHZrAwCgYIKoZIzj0EAwMwWjELMAkGA1UEBhMCWFYxDTALBgNVBAgMBHRlc3QxDjAMBgNVBAcMBUluZGlhMQwwCgYDVQQKDANXSE8xEDAOBgNVBAsMB09wc3RlYW0xDDAKBgNVBAMMA1NDQTAeFw0yNTEwMjAxMDUzMzdaFw0yOTEwMTkxMDUzMzdaMFoxCzAJBgNVBAYTAlhWMQ0wCwYDVQQIDAR0ZXN0MQ4wDAYDVQQHDAVJbmRpYTEMMAoGA1UECgwDV0hPMRAwDgYDVQQLDAdPcHN0ZWFtMQwwCgYDVQQDDANTQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATEWCv+9opPsLf4eh5h5N+nLfgPOrIxXuqokW27vBtXuCKCO6VHyKHOqQ8IdPE0LZbISH1qfKxDmIIxRTh1hRW8o0UwQzASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUwSIwTtcZKJQGgEoJlw8KUix3ef8wCgYIKoZIzj0EAwMDSQAwRgIhAJrA2OvM1CaKvgWmoFUQ99Kr7yhTjtAh+HKS98+hZVHmAiEA9HYIEfGy2tTMcpMOV8AnF6kxWqYMk2myhzpMoDC9ROo="],"crv":"P-256","x":"APtrrh5hD9Hr1NBkjmWnwipIG1W0JGKQSe2kJBpGW-lO","y":"AJItI3ON25bI15nTLu1u86RWf5J4y2QUFHY4hSIXIgJj"},"domain":"DCC","participant":"XV","keyusage":"DSC"}],"proof":{"type":"JsonWebSignature2020","created":"2025-12-06T12:00:18Z","nonce":"xmjBk4PLBwavYhiMk2RFSTwpJCuaJ9iI","proofPurpose":"assertionMethod","verificationMethod":"did:web:raw.githubusercontent.com:WorldHealthOrganization:tng-participants-dev:main:WHO:signing:DID","jws":"eyJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdLCJhbGciOiJFUzI1NiJ9..MEQCIFYZhW71NqNntgfYtmLULNrllLDKjycQGhAUCdncWxmzAiBS3SLNQjU76uS-qF82yRh2lFSPlYU6GOGOewPY89p3yQ"}}

=== WorldHealthOrganization/tng-cdn-dev/v2/trustlist/DCC/XB/did.json
{"@context":["https://www.w3.org/ns/did/v1","https://w3id.org/security/suites/jws-2020/v1","https://worldhealthorganization.github.io/smart-trust/tng-additional-context/v1"],"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:DCC:XB","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:DCC","verificationMethod":[{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:DCC:XB:SCA#UtbQjTdyhMA=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:DCC","publicKeyJwk":{"kty":"EC","kid":"UtbQjTdyhMA=","x5c":["MIICEDCCAbWgAwIBAgIUF8kxuZF7adI6n7Wj6o9d6sx9TxIwCgYIKoZIzj0EAwIwZDELMAkGA1UEBhMCWEIxEzARBgNVBAgMClRlc3QgU3RhdGUxDTALBgNVBAcMBFRFU1QxDDAKBgNVBAoMA1dITzEMMAoGA1UECwwDUiZEMRUwEwYDVQQDDAxOYXRpb25YQl9UTlAwHhcNMjUwNTI4MDUxMDQ4WhcNMjkwNTI4MDUxMDQ4WjBkMQswCQYDVQQGEwJYQjETMBEGA1UECAwKVGVzdCBTdGF0ZTENMAsGA1UEBwwEVEVTVDEMMAoGA1UECgwDV0hPMQwwCgYDVQQLDANSJkQxFTATBgNVBAMMDE5hdGlvblhCX1ROUDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFLx7QLZrgVVmq55yO3iZ8uWnJdSSfeTmrsyWAb0lUFcNvngFcpXPLA2+Q89A8pgjiAbeCvA+v589ZTbnD0sKAejRTBDMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBTil6VV5lPoLhiXm0swDHAnxcHnHjAKBggqhkjOPQQDAgNJADBGAiEAi6iQ6WE/6a2aCLWp6HoDSYm4U9Fkuj6Sv57NAjJqY2sCIQCkgtLYg11QAeHby7m2eNHWtg0slAqDAC5DPvXJMFRe+g=="],"crv":"P-256","x":"UvHtAtmuBVWarnnI7eJny5acl1JJ95OauzJYBvSVQVw","y":"NvngFcpXPLA2-Q89A8pgjiAbeCvA-v589ZTbnD0sKAc"},"domain":"DCC","participant":"XB","keyusage":"SCA"},{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:DCC:XB:DESC#fESlKlyv1ZY=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:DCC","publicKeyJwk":{"kty":"EC","kid":"fESlKlyv1ZY=","x5c":["MIIB8jCCAZegAwIBAgIUdrWof+iQo0AtgirPiTTdeVOrPX0wCgYIKoZIzj0EAwIwZDELMAkGA1UEBhMCWEIxEzARBgNVBAgMClRlc3QgU3RhdGUxDTALBgNVBAcMBFRFU1QxDDAKBgNVBAoMA1dITzEMMAoGA1UECwwDUiZEMRUwEwYDVQQDDAxOYXRpb25YQl9UTlAwHhcNMjUwNTI4MDUzNTE5WhcNMjcwNTI4MDUzNTE5WjBkMQswCQYDVQQGEwJYQjETMBEGA1UECAwKVGVzdCBTdGF0ZTENMAsGA1UEBwwEVEVTVDEMMAoGA1UECgwDV0hPMQwwCgYDVQQLDANSJkQxFTATBgNVBAMMDE5hdGlvblhCX1ROUDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABAn7qNLvMRLjxpUDTBjBYRw3zXOZajLCRt7+38A4I1sMQmMyvM16SruF2iIyQcEOPJhLURqoR6Pa5sOwFtQfzSijJzAlMA4GA1UdDwEB/wQEAwIChDATBgNVHSUEDDAKBggrBgEFBQcDAjAKBggqhkjOPQQDAgNJADBGAiEA0zIiyHwxPo+5OAaCq8OMY3K/FPtMX8CbeIl3gErPKVcCIQDAjCEWxLBdUV6UeysmS0yoErHteXJc6147vlB9gtHavQ==","MIIB8jCCAZegAwIBAgIUYETlKy3eYs+cIEWGWbctYG44LwgwCgYIKoZIzj0EAwIwZDELMAkGA1UEBhMCWEIxEzARBgNVBAgMClRlc3QgU3RhdGUxDTALBgNVBAcMBFRFU1QxDDAKBgNVBAoMA1dITzEMMAoGA1UECwwDUiZEMRUwEwYDVQQDDAxOYXRpb25YQl9UTlAwHhcNMjUwNTI4MDUxMDQ4WhcNMjkwNTI4MDUxMDQ4WjBkMQswCQYDVQQGEwJYQjETMBEGA1UECAwKVGVzdCBTdGF0ZTENMAsGA1UEBwwEVEVTVDEMMAoGA1UECgwDV0hPMQwwCgYDVQQLDANSJkQxFTATBgNVBAMMDE5hdGlvblhCX1ROUDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABIMmZeYgJu6a3xRodxDx6ccN/VzfY83sWHf32s9INgbqCFnJUw8GrxkFGuckvPmExxIDZPmwd0NxzcHmgdm09RKjJzAlMA4GA1UdDwEB/wQEAwIChDATBgNVHSUEDDAKBggrBgEFBQcDAjAKBggqhkjOPQQDAgNJADBGAiEA3M34MFYJ9ixe1+sDQgGGTss7ZdUa4rKjrz9tbMEd6gICIQDBaXJFSyfdLN4I0CvaPlcXBUy3agVUTgepCozNbtdpOA=="],"crv":"P-256","x":"Cfuo0u8xEuPGlQNMGMFhHDfNc5lqMsJG3v7fwDgjWww","y":"QmMyvM16SruF2iIyQcEOPJhLURqoR6Pa5sOwFtQfzSg"},"domain":"DCC","participant":"XB","keyusage":"DESC"},{"id":"did:web:tng-cdn-dev.who.int:v2:trustlist:DCC:XB:DECA#sMaCYKqD7Cc=","type":"JsonWebKey2020","controller":"did:web:tng-cdn-dev.who.int:v2:trustlist:DCC","publicKeyJwk":{"kty":"EC","kid":"sMaCYKqD7Cc=","x5c":["MIIB8jCCAZegAwIBAgIUYETlKy3eYs+cIEWGWbctYG44LwgwCgYIKoZIzj0EAwIwZDELMAkGA1UEBhMCWEIxEzARBgNVBAgMClRlc3QgU3RhdGUxDTALBgNVBAcMBFRFU1QxDDAKBgNVBAoMA1dITzEMMAoGA1UECwwDUiZEMRUwEwYDVQQDDAxOYXRpb25YQl9UTlAwHhcNMjUwNTI4MDUxMDQ4WhcNMjkwNTI4MDUxMDQ4WjBkMQswCQYDVQQGEwJYQjETMBEGA1UECAwKVGVzdCBTdGF0ZTENMAsGA1UEBwwEVEVTVDEMMAoGA1UECgwDV0hPMQwwCgYDVQQLDANSJkQxFTATBgNVBAMMDE5hdGlvblhCX1ROUDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABIMmZeYgJu6a3xRodxDx6ccN/VzfY83sWHf32s9INgbqCFnJUw8GrxkFGuckvPmExxIDZPmwd0NxzcHmgdm09RKjJzAlMA4GA1UdDwEB/wQEAwIChDATBgNVHSUEDDAKBggrBgEFBQcDAjAKBggqhkjOPQQDAgNJADBGAiEA3M34MFYJ9ixe1+sDQgGGTss7ZdUa4rKjrz9tbMEd6gICIQDBaXJFSyfdLN4I0CvaPlcXBUy3agVUTgepCozNbtdpOA=="],"crv":"P-256","x":"AIMmZeYgJu6a3xRodxDx6ccN_VzfY83sWHf32s9INgbq","y":"CFnJUw8GrxkFGuckvPmExxIDZPmwd0NxzcHmgdm09RI"},"domain":"DCC","participant":"XB","keyusage":"DECA"}],"proof":{"type":"JsonWebSignature2020","created":"2026-01-04T06:00:11Z","nonce":"WtNKDyDA1g2AKFSlF07E12HV2j0J0em1","proofPurpose":"assertionMethod","verificationMethod":"did:web:raw.githubusercontent.com:WorldHealthOrganization:tng-participants-dev:main:WHO:signing:DID","jws":"eyJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdLCJhbGciOiJFUzI1NiJ9..MEQCIBLD9fl_OrsutP5DvqFg_vsoi6mFOA-pPZBz7gX3aIRxAiAKtBO6_Y3OBQKw55gfv4TiQpv577qtX5wfku4f6mBBnA"}}
